# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile for bootstrapping a Jepsen test cluster

VAGRANTFILE_API_VERSION = "2"
BOX_MEM = ENV['BOX_MEM'] || "1024"
BOX_NAME = ENV['BOX_NAME'] || "debian/jessie64"
CLUSTER_HOSTS = ENV['CLUSTER_HOSTS'] || "debian"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Configure 5 Jepsen test nodes and a controller node
  config.vm.define :n0 do |n0_config|
    n0_config.vm.box = BOX_NAME
    n0_config.vm.network :private_network, ip: "192.168.122.10"
    n0_config.vm.hostname = "n0.local"
    n0_config.ssh.forward_agent = true
    n0_config.vm.provider "virtualbox" do |v|
      v.name = "jepsen-test-controller"
      v.customize ["modifyvm", :id, "--memory", BOX_MEM]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    n0_config.vm.provision :hosts do |provisioner|
        provisioner.add_host '192.168.122.10', ['n0.local']
        provisioner.add_host '192.168.122.11', ['n1.local']
        provisioner.add_host '192.168.122.13', ['n2.local']
        provisioner.add_host '192.168.122.14', ['n3.local']
        provisioner.add_host '192.168.122.15', ['n4.local']
        provisioner.add_host '192.168.122.16', ['n5.local']
    end
  end
  config.vm.define :n1 do |n1_config|
    n1_config.vm.box = BOX_NAME
    n1_config.vm.network :private_network, ip: "192.168.122.11"
    n1_config.vm.hostname = "n1.local"
    n1_config.ssh.forward_agent = true
    n1_config.vm.provider "virtualbox" do |v|
      v.name = "jepsen-test-n1"
      v.customize ["modifyvm", :id, "--memory", BOX_MEM]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    n1_config.vm.provision :hosts do |provisioner|
      provisioner.add_host '192.168.122.10', ['n0.local']
      provisioner.add_host '192.168.122.11', ['n1.local']
      provisioner.add_host '192.168.122.13', ['n2.local']
      provisioner.add_host '192.168.122.14', ['n3.local']
      provisioner.add_host '192.168.122.15', ['n4.local']
      provisioner.add_host '192.168.122.16', ['n5.local']
    end
  end
  config.vm.define :n2 do |n2_config|
    n2_config.vm.box = BOX_NAME
    n2_config.vm.network :private_network, ip: "192.168.122.12"
    n2_config.vm.hostname = "n2.local"
    n2_config.ssh.forward_agent = true
    n2_config.vm.provider "virtualbox" do |v|
      v.name = "jepsen-test-n2"
      v.customize ["modifyvm", :id, "--memory", BOX_MEM]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    n2_config.vm.provision :hosts do |provisioner|
      provisioner.add_host '192.168.122.10', ['n0.local']
      provisioner.add_host '192.168.122.11', ['n1.local']
      provisioner.add_host '192.168.122.13', ['n2.local']
      provisioner.add_host '192.168.122.14', ['n3.local']
      provisioner.add_host '192.168.122.15', ['n4.local']
      provisioner.add_host '192.168.122.16', ['n5.local']
    end
  end
  config.vm.define :n3 do |n3_config|
    n3_config.vm.box = BOX_NAME
    n3_config.vm.network :private_network, ip: "192.168.122.13"
    n3_config.vm.hostname = "n3.local"
    n3_config.ssh.forward_agent = true
    n3_config.vm.provider "virtualbox" do |v|
      v.name = "jepsen-test-n3"
      v.customize ["modifyvm", :id, "--memory", BOX_MEM]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    n3_config.vm.provision :hosts do |provisioner|
      provisioner.add_host '192.168.122.10', ['n0.local']
      provisioner.add_host '192.168.122.11', ['n1.local']
      provisioner.add_host '192.168.122.13', ['n2.local']
      provisioner.add_host '192.168.122.14', ['n3.local']
      provisioner.add_host '192.168.122.15', ['n4.local']
      provisioner.add_host '192.168.122.16', ['n5.local']
    end
  end
  config.vm.define :n4 do |n4_config|
    n4_config.vm.box = BOX_NAME
    n4_config.vm.network :private_network, ip: "192.168.122.14"
    n4_config.vm.hostname = "n4.local"
    n4_config.ssh.forward_agent = true
    n4_config.vm.provider "virtualbox" do |v|
      v.name = "jepsen-test-n4"
      v.customize ["modifyvm", :id, "--memory", BOX_MEM]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    n4_config.vm.provision :hosts do |provisioner|
      provisioner.add_host '192.168.122.10', ['n0.local']
      provisioner.add_host '192.168.122.11', ['n1.local']
      provisioner.add_host '192.168.122.13', ['n2.local']
      provisioner.add_host '192.168.122.14', ['n3.local']
      provisioner.add_host '192.168.122.15', ['n4.local']
      provisioner.add_host '192.168.122.16', ['n5.local']
    end
  end
  config.vm.define :n5 do |n5_config|
    n5_config.vm.box = BOX_NAME
    n5_config.vm.network :private_network, ip: "192.168.122.15"
    n5_config.vm.hostname = "n5.local"
    n5_config.ssh.forward_agent = true
    n5_config.vm.provider "virtualbox" do |v|
      v.name = "jepsen-test-n5"
      v.customize ["modifyvm", :id, "--memory", BOX_MEM]
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--cpus", "2"]
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    n5_config.vm.provision :hosts do |provisioner|
      provisioner.add_host '192.168.122.10', ['n0.local']
      provisioner.add_host '192.168.122.11', ['n1.local']
      provisioner.add_host '192.168.122.13', ['n2.local']
      provisioner.add_host '192.168.122.14', ['n3.local']
      provisioner.add_host '192.168.122.15', ['n4.local']
      provisioner.add_host '192.168.122.16', ['n5.local']
    end
    # Bit of a hack since VirtualBox does not support parallel provisioning
    n5_config.vm.provision :ansible do |ansible|
      ansible.inventory_path = CLUSTER_HOSTS
      # Extra Ansible variables can be defined here
      # (equivalent to ansible-playbook '--extra-vars' command line option)
      #ansible.extra_vars = {
      #  jepsen_node_ram: 2048,
      #}
      ansible.playbook = "jepsen_init.yml"
      ansible.limit = "all"
    end
  end
end
